lista_materia = [
    {"Código": "BPTSP05", "Nombre": "ALGORITMOS Y PROGRAMACION", "Secciones": 5},
    {"Código": "FPTSP01", "Nombre": "BASES DE DATOS I", "Secciones": 2},
    {"Código": "FPTSP26", "Nombre": "BASES DE DATOS II", "Secciones": 2},
    {"Código": "FPTSP25", "Nombre": "COMPUTACION EMERGENTE", "Secciones": 1},
    {"Código": "FGESP03", "Nombre": "CONTENIDOS DIGITALES PARA EL METAVERSO", "Secciones": 2},
    {"Código": "BPTSP06", "Nombre": "ESTRUCTURAS DE DATOS", "Secciones": 3},
    {"Código": "FPTPS07", "Nombre": "INGENIERIA DE SOFTWARE", "Secciones": 2},
    {"Código": "FPTSP15", "Nombre": "INGENIERIA ECONOMICA", "Secciones": 2},
    {"Código": "FGESP05", "Nombre": "INTERNSHIP", "Secciones": 1},
    {"Código": "FBTSP03", "Nombre": "INTRODUCCION A LA INGENIERIA", "Secciones": 8},
    {"Código": "FPSSP02", "Nombre": "IP EVAL. DE NEG Y PROYECTOS DE INVERSIÓN", "Secciones": 1},
    {"Código": "FPSSP03", "Nombre": "IS AGILIDAD EN LA CALIDAD DEL SOFTWARE", "Secciones": 1},
    {"Código": "FPSSP04", "Nombre": "IS EL HACKER ÉTICO", "Secciones": 1},
    {"Código": "FPTSP21", "Nombre": "MODELAC. DE SISTEMAS EN REDES", "Secciones": 1},
    {"Código": "FGESP07", "Nombre": "MODELADO ARTÍSTICO 3D", "Secciones": 1},
    {"Código": "FGESP01", "Nombre": "NEGOCIOS WEB", "Secciones": 1},
    {"Código": "FPTSP17", "Nombre": "OPTIMIZACION I", "Secciones": 3},
    {"Código": "FPTSP19", "Nombre": "OPTIMIZACION II", "Secciones": 1},
    {"Código": "BPTSP03", "Nombre": "ORGANIZACION DEL COMPUTADOR", "Secciones": 1},
    {"Código": "FBTSP04", "Nombre": "PENSAMIENTO COMPUTACIONAL", "Secciones": 17},
    {"Código": "FPTSP14", "Nombre": "PROYECTOS DE INGENIERIA", "Secciones": 2},
    {"Código": "FPTSP20", "Nombre": "SIMULACIÓN", "Secciones": 3},
    {"Código": "FPTSP23", "Nombre": "SISTEMAS DE APOYO", "Secciones": 1},
    {"Código": "FPTSP04", "Nombre": "SISTEMAS DE INFORMACION", "Secciones": 1},
    {"Código": "FPTSP28", "Nombre": "SISTEMAS DISTRIBUIDOS", "Secciones": 1},
    {"Código": "BPTSP04", "Nombre": "SISTEMAS OPERATIVOS", "Secciones": 2},
    {"Código": "FPTSP22", "Nombre": "TALLER DE TRABAJO DE GRADO - INGENIERÍA", "Secciones": 3},
    {"Código": "BPTSP05", "Nombre": "ALGORITMOS Y PROGRAMACION", "Secciones": 6},
    {"Código": "FPTSP27", "Nombre": "ANÁLISIS DE DATOS", "Secciones": 2},
    {"Código": "FPTSP26", "Nombre": "BASES DE DATOS II", "Secciones": 2},
    {"Código": "FPTSP25", "Nombre": "COMPUTACION EMERGENTE", "Secciones": 1},
    {"Código": "FGESP03", "Nombre": "CONTENIDOS DIGITALES PARA EL METAVERSO", "Secciones": 1},
    {"Código": "FGESP06", "Nombre": "DESARROLLO ENTORNOS TRIDIM. INTERACTIVOS", "Secciones": 1},
    {"Código": "BPTSP06", "Nombre": "ESTRUCTURAS DE DATOS", "Secciones": 3},
    {"Código": "FPTSP24", "Nombre": "GERENCIA DE CONSTRUCCIÓN", "Secciones": 1},
    {"Código": "FPTSP11", "Nombre": "GERENCIA DE PROYECTOS TIC", "Secciones": 1},
    {"Código": "FPTSP07", "Nombre": "INGENIERIA DE SOFTWARE", "Secciones": 2},
    {"Código": "FPTSP15", "Nombre": "INGENIERIA ECONOMICA", "Secciones": 2},
    {"Código": "FGESP05", "Nombre": "INTERNSHIP", "Secciones": 1},
    {"Código": "FBTSP03", "Nombre": "INTRODUCCION A LA INGENIERIA", "Secciones": 1},
    {"Código": "FGESP04", "Nombre": "INTRODUCCIÓN A LA REALIDAD VIRTUAL", "Secciones": 1},
    {"Código": "FPSSP04", "Nombre": "IS EL HACKER ÉTICO", "Secciones": 1},
    {"Código": "FPTSP21", "Nombre": "MODELAC. DE SISTEMAS EN REDES", "Secciones": 1},
    {"Código": "FGESP07", "Nombre": "MODELADO ARTÍSTICO 3D", "Secciones": 1},
    {"Código": "FGESP01", "Nombre": "NEGOCIOS WEB", "Secciones": 1},
    {"Código": "FPTSP17", "Nombre": "OPTIMIZACION I", "Secciones": 3},
    {"Código": "FPTSP19", "Nombre": "OPTIMIZACION II", "Secciones": 2},
    {"Código": "BPTSP03", "Nombre": "ORGANIZACION DEL COMPUTADOR", "Secciones": 2},
    {"Código": "FBTSP04", "Nombre": "PENSAMIENTO COMPUTACIONAL", "Secciones": 6},
    {"Código": "FPTSP14", "Nombre": "PROYECTOS DE INGENIERIA", "Secciones": 2},
    {"Código": "FPTSP18", "Nombre": "SEGURIDAD DE LA INFORMACIÖN", "Secciones": 2},
    {"Código": "FPTSP20", "Nombre": "SIMULACIÓN", "Secciones": 2},
    {"Código": "FPTSP23", "Nombre": "SISTEMAS DE APOYO", "Secciones": 2},
    {"Código": "FPTSP04", "Nombre": "SISTEMAS DE INFORMACION", "Secciones": 2},
    {"Código": "FPTSP28", "Nombre": "SISTEMAS DISTRIBUIDOS", "Secciones": 1},
    {"Código": "BPTSP04", "Nombre": "SISTEMAS OPERATIVOS", "Secciones": 2},
    {"Código": "FPTSP22", "Nombre": "TALLER DE TRABAJO DE GRADO - INGENIERÍA", "Secciones": 3},
    {"Código": "BPTSP05", "Nombre": "ALGORITMOS Y PROGRAMACION", "Secciones": 5},
    {"Código": "FPTSP01", "Nombre": "BASES DE DATOS I", "Secciones": 2},
    {"Código": "FPTSP26", "Nombre": "BASES DE DATOS II", "Secciones": 2},
    {"Código": "FPTSP25", "Nombre": "COMPUTACION EMERGENTE", "Secciones": 1},
    {"Código": "FGESP03", "Nombre": "CONTENIDOS DIGITALES PARA EL METAVERSO", "Secciones": 2},
    {"Código": "BPTSP06", "Nombre": "ESTRUCTURAS DE DATOS", "Secciones": 3},
    {"Código": "FPTPS07", "Nombre": "INGENIERIA DE SOFTWARE", "Secciones": 2},
    {"Código": "FPTSP15", "Nombre": "INGENIERIA ECONOMICA", "Secciones": 2},
    {"Código": "FGESP05", "Nombre": "INTERNSHIP", "Secciones": 1},
    {"Código": "FBTSP03", "Nombre": "INTRODUCCION A LA INGENIERIA", "Secciones": 8},
    {"Código": "FPSSP02", "Nombre": "IP EVAL. DE NEG Y PROYECTOS DE INVERSIÓN", "Secciones": 1},
    {"Código": "FPSSP03", "Nombre": "IS AGILIDAD EN LA CALIDAD DEL SOFTWARE", "Secciones": 1},
    {"Código": "FPSSP04", "Nombre": "IS EL HACKER ÉTICO", "Secciones": 1},
    {"Código": "FPTSP21", "Nombre": "MODELAC. DE SISTEMAS EN REDES", "Secciones": 1},
    {"Código": "FGESP07", "Nombre": "MODELADO ARTÍSTICO 3D", "Secciones": 1},
    {"Código": "FGESP01", "Nombre": "NEGOCIOS WEB", "Secciones": 1},
    {"Código": "FPTSP17", "Nombre": "OPTIMIZACION I", "Secciones": 3},
    {"Código": "FPTSP19", "Nombre": "OPTIMIZACION II", "Secciones": 1},
    {"Código": "BPTSP03", "Nombre": "ORGANIZACION DEL COMPUTADOR", "Secciones": 1},
    {"Código": "FBTSP04", "Nombre": "PENSAMIENTO COMPUTACIONAL", "Secciones": 17},
    {"Código": "FPTSP14", "Nombre": "PROYECTOS DE INGENIERIA", "Secciones": 2},
    {"Código": "FPTSP20", "Nombre": "SIMULACIÓN", "Secciones": 3},
    {"Código": "FPTSP23", "Nombre": "SISTEMAS DE APOYO", "Secciones": 1},
    {"Código": "FPTSP04", "Nombre": "SISTEMAS DE INFORMACION", "Secciones": 1},
    {"Código": "FPTSP28", "Nombre": "SISTEMAS DISTRIBUIDOS", "Secciones": 1},
    {"Código": "BPTSP04", "Nombre": "SISTEMAS OPERATIVOS", "Secciones": 2},
    {"Código": "FPTSP22", "Nombre": "TALLER DE TRABAJO DE GRADO - INGENIERÍA", "Secciones": 3},
    {"Código": "BPTSP05", "Nombre": "ALGORITMOS Y PROGRAMACION", "Secciones": 6},
    {"Código": "FPTSP01", "Nombre": "BASES DE DATOS I", "Secciones": 4},
    {"Código": "FPTSP25", "Nombre": "COMPUTACION EMERGENTE", "Secciones": 2},
    {"Código": "FGESP03", "Nombre": "CONTENIDOS DIGITALES PARA EL METAVERSO", "Secciones": 1},
    {"Código": "FGESP06", "Nombre": "DESARROLLO ENTORNOS TRIDIM. INTERACTIVOS", "Secciones": 1},
    {"Código": "BPTSP06", "Nombre": "ESTRUCTURAS DE DATOS", "Secciones": 2},
    {"Código": "FPTSP24", "Nombre": "GERENCIA DE CONSTRUCCIÓN", "Secciones": 1},
    {"Código": "FPTSP11", "Nombre": "GERENCIA DE PROYECTOS TIC", "Secciones": 2},
    {"Código": "FPTSP07", "Nombre": "INGENIERIA DE SOFTWARE", "Secciones": 2},
    {"Código": "FPTSP15", "Nombre": "INGENIERIA ECONOMICA", "Secciones": 2},
    {"Código": "FBTSP03", "Nombre": "INTRODUCCION A LA INGENIERIA", "Secciones": 1},
    {"Código": "FPSSP01", "Nombre": "IS DESARROLLO SOLUC. INFORMATICAS EMPRES", "Secciones": 1},
    {"Código": "FPTSP21", "Nombre": "MODELAC. DE SISTEMAS EN REDES", "Secciones": 1},
    {"Código": "FGESP01", "Nombre": "NEGOCIOS WEB", "Secciones": 1},
    {"Código": "FPTSP17", "Nombre": "OPTIMIZACION I", "Secciones": 2},
    {"Código": "FPTSP19", "Nombre": "OPTIMIZACION II", "Secciones": 2},
    {"Código": "BPTSP03", "Nombre": "ORGANIZACION DEL COMPUTADOR", "Secciones": 2},
    {"Código": "FBTSP04", "Nombre": "PENSAMIENTO COMPUTACIONAL", "Secciones": 7},
    {"Código": "FPTSP14", "Nombre": "PROYECTOS DE INGENIERIA", "Secciones": 3},
    {"Código": "FPTSP18", "Nombre": "SEGURIDAD DE LA INFORMACIÖN", "Secciones": 1},
    {"Código": "FPTSP20", "Nombre": "SIMULACIÓN", "Secciones": 2},
    {"Código": "FPTSP04", "Nombre": "SISTEMAS DE INFORMACION", "Secciones": 1},
    {"Código": "FPTSP28", "Nombre": "SISTEMAS DISTRIBUIDOS", "Secciones": 1},
    {"Código": "FPTSP22", "Nombre": "TALLER DE TRABAJO DE GRADO - INGENIERÍA", "Secciones": 3}
]
