class relacion:
    def __init__(self, profesor, materia):
        self.profesor = profesor
        self.materia = materia 
relacion_final = [
    {"profesor": "ENCARNACION VEGA", "materias": ["SEGURIDAD DE LA INFORMACIÖN"]},
    {"profesor": "IVAN MUÑOZ", "materias": ["INTRODUCCION A LA INGENIERIA"]},
    {"profesor": "MONTSERRAT CAMPOS", "materias": ["INTRODUCCION A LA INGENIERIA", "PROYECTOS DE INGENIERIA"]},
    {"profesor": "MARIA PEÑA", "materias": ["INTRODUCCION A LA INGENIERIA", "GERENCIA de CONSTRUCCIÓN"]},
    {"profesor": "SARA MENDEZ", "materias": ["INTRODUCCION A LA INGENIERIA"]},
    {"profesor": "ROCIO RUBIO", "materias": ["PROYECTOS DE INGENIERIA"]},
    {"profesor": "IVAN DURAN", "materias": ["OPTIMIZACION I", "OPTIMIZACION II", "SIMULACIÓN", "SISTEMAS DE APOYO"]},
    {"profesor": "DAVID FLORES", "materias": ["TALLER DE TRABAJO DE GRADO - INGENIERÍA"]},
    {"profesor": "IVAN BENITEZ", "materias": ["TALLER DE TRABAJO DE GRADO - INGENIERÍA"]},
    {"profesor": "NURIA VIDAL", "materias": ["TALLER DE TRABAJO DE GRADO - INGENIERÍA"]},
    {"profesor": "ANDRES MONTERO", "materias": ["NEGOCIOS WEB"]},
    {"profesor": "SARA MENDOZA", "materias": ["ALGORITMOS Y PROGRAMACION", "ESTRUCTURAS DE DATOS", "COMPUTACION EMERGENTE"]},
    {"profesor": "JULIA JIMENEZ", "materias": ["ALGORITMOS Y PROGRAMACION"]},
    {"profesor": "IVAN LORENZO", "materias": ["ALGORITMOS Y PROGRAMACION"]},
    {"profesor": "CARMEN HIDALGO", "materias": ["ALGORITMOS Y PROGRAMACION"]},
    {"profesor": "MONICA PASCUAL", "materias": ["ALGORITMOS Y PROGRAMACION"]},
    {"profesor": "CARMEN VICENTE", "materias": ["ALGORITMOS Y PROGRAMACION", "PENSAMIENTO COMPUTACIONAL"]},
    {"profesor": "ALBA CASTILLO", "materias": ["CONTENIDOS DIGITALES PARA EL METAVERSO"]},
    {"profesor": "MARIA TORRES", "materias": ["CONTENIDOS DIGITALES PARA EL METAVERSO", "INTRODUCCIÓN A LA REALIDAD VIRTUAL"]},
    {"profesor": "LAURA GUERRERO", "materias": ["ESTRUCTURAS DE DATOS"]},
    {"profesor": "DANIEL CORTES", "materias": ["ALGORITMOS Y PROGRAMACION", "ESTRUCTURAS DE DATOS"]},
    {"profesor": "SANTIAGO LOPEZ", "materias": ["COMPUTACION EMERGENTE"]},
    {"profesor": "JULIA MEDINA", "materias": ["SISTEMAS OPERATIVOS"]},
    {"profesor": "VICENTE BRAVO", "materias": ["SIMULACIÓN"]},
    {"profesor": "ANDREA MOYA", "materias": ["OPTIMIZACION I", "OPTIMIZACION II"]},
    {"profesor": "PAULA CRESPO", "materias": ["PENSAMIENTO COMPUTACIONAL", "SISTEMAS DE INFORMACION"]},
    {"profesor": "RUBEN FERRER", "materias": ["ALGORITMOS Y PROGRAMACION", "PENSAMIENTO COMPUTACIONAL", "SISTEMAS DE INFORMACION", "INGENIERIA DE SOFTWARE"]},
    {"profesor": "ENRIQUE VAZQUEZ", "materias": ["PENSAMIENTO COMPUTACIONAL", "INGENIERIA DE SOFTWARE"]},
    {"profesor": "ROSARIO GIL", "materias": ["IP EVAL. DE NEG Y PROYECTOS DE INVERSIÓN", "INGENIERIA ECONOMICA"]},
    {"profesor": "RAMON CALVO", "materias": ["ORGANIZACION DEL COMPUTADOR", "INGENIERIA ECONOMICA", "MODELAC. DE SISTEMAS EN REDES"]},
    {"profesor": "ENRIQUE PASCUAL", "materias": ["IS AGILIDAD EN LA CALIDAD DEL SOFTWARE", "GERENCIA DE PROYECTOS TIC"]},
    {"profesor": "TERESA MORALES", "materias": ["PENSAMIENTO COMPUTACIONAL"]},
    {"profesor": "SERGIO CABALLERO", "materias": ["PENSAMIENTO COMPUTACIONAL"]},
    {"profesor": "ISABEL CASTRO", "materias": ["PENSAMIENTO COMPUTACIONAL", "BASES DE DATOS I"]},
    {"profesor": "LUIS RUIZ", "materias": ["PENSAMIENTO COMPUTACIONAL"]},
    {"profesor": "ADRIAN SANTIAGO", "materias": ["PENSAMIENTO COMPUTACIONAL"]},
    {"profesor": "JOAQUIN LOZANO", "materias": ["PENSAMIENTO COMPUTACIONAL", "IS EL HACKER ÉTICO", "SEGURIDAD DE LA INFORMACIÖN"]},
    {"profesor": "MARIO GIMENEZ", "materias": ["BASES DE DATOS I", "BASES DE DATOS II"]},
    {"profesor": "CARMEN HERNANDEZ", "materias": ["ORGANIZACION DEL COMPUTADOR"]},
    {"profesor": "IVAN ORTEGA", "materias": ["PROYECTOS DE INGENIERIA"]},
    {"profesor": "PILAR PARRA", "materias": ["ALGORITMOS Y PROGRAMACION"]},
    {"profesor": "JUAN VELASCO", "materias": ["INGENIERIA ECONOMICA"]},
    {"profesor": "IVAN VARGAS", "materias": ["INTRODUCCION A LA INGENIERIA"]},
    {"profesor": "JUANA IBAÑEZ", "materias": ["INTRODUCCION A LA INGENIERIA"]},
    {"profesor": "MARINA NAVARRO", "materias": ["TALLER DE TRABAJO DE GRADO - INGENIERÍA"]},
    {"profesor": "PILAR MEDINA", "materias": ["SISTEMAS OPERATIVOS"]},
    {"profesor": "JULIA PARDO", "materias": ["OPTIMIZACION I", "OPTIMIZACION II", "SIMULACIÓN", "SISTEMAS DE APOYO"]},
    {"profesor": "ANTONIO LEON", "materias": ["PENSAMIENTO COMPUTACIONAL"]},
    {"profesor": "RAUL GALLEGO", "materias": ["IS DESARROLLO SOLUC. INFORMATICAS EMPRES", "ANÁLISIS DE DATOS"]},
    {"profesor": "MARIA PEREZ", "materias": ["IS DESARROLLO SOLUC. INFORMATICAS EMPRES"]},
    {"profesor": "MARTA MARTIN", "materias": ["INTERNSHIP"]},
    {"profesor": "CARMEN RIVERA", "materias": ["ALGORITMOS Y PROGRAMACION", "SISTEMAS DISTRIBUIDOS"]},
    {"profesor": "ALICIA IGLESIAS", "materias": ["INTERNSHIP"]},
    {"profesor": "VICTOR ALONSO", "materias": ["ALGORITMOS Y PROGRAMACION", "ESTRUCTURAS DE DATOS"]},
    {"profesor": "IRENE DURAN", "materias": ["ALGORITMOS Y PROGRAMACION", "PENSAMIENTO COMPUTACIONAL", "INTRODUCCIÓN A LA REALIDAD VIRTUAL", "DESARROLLO ENTORNOS TRIDIM. INTERACTIVOS"]},
    {"profesor": "JORGE RAMIREZ", "materias": ["INTRODUCCION A LA INGENIERIA"]},
    {"profesor": "DIEGO CANO", "materias": ["INTRODUCCION A LA INGENIERIA"]},
    {"profesor": "IVAN DIEZ", "materias": ["PROYECTOS DE INGENIERIA"]},
    {"profesor": "FRANCISCA GARRIDO", "materias": ["MODELADO ARTÍSTICO 3D"]},
    {"profesor": "MERCEDES DOMINGUEZ", "materias": ["ALGORITMOS Y PROGRAMACION", "PENSAMIENTO COMPUTACIONAL"]},
    {"profesor": "HUGO CANO", "materias": ["PENSAMIENTO COMPUTACIONAL"]},
    {"profesor": "FERNANDO CARMONA", "materias": ["IP EVAL. DE NEG Y PROYECTOS DE INVERSIÓN"]},
    {"profesor": "ELENA NIETO", "materias": ["SISTEMAS OPERATIVOS"]},
    {"profesor": "JESUS MORENO", "materias": ["ANÁLISIS DE DATOS"]}
]